apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pelias-slackbot-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: pelias-slackbot
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: pelias-slackbot
    spec:
      containers:
      - name: slackbot
        image: pelias/slack-search-app:master-2017-09-22-1a949a1dd18a24866198d4fcbb6fea7affb8ef62
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /search?text=foo
            port: 3000
        resources:
          limits:
            cpu:    0.1
            memory: 512Mi
          requests:
            cpu:    0.1
            memory: 256Mi
        env:
          - name: GITHUB_AUTH
            valueFrom:
              secretKeyRef:
                name: slackbot
                key: GITHUB_AUTH
          - name: SEARCH_API_KEY
            valueFrom:
              secretKeyRef:
                 name: slackbot
                 key: SEARCH_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  name: pelias-slackbot-public-service
spec:
  selector:
    app: pelias-slackbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
