apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash-elasticsearch-deployment
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-elasticsearch
  template:
    metadata:
      labels:
        app: logstash-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: pelias/elasticsearch
        ports:
        - containerPort: 9200
        resources:
          limits:
            cpu:    1.0
            memory: 500Mi
          requests:
            cpu:    0.5
            memory: 300Mi
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-elasticsearch-service
  namespace: logging
spec:
  selector:
    app: logstash-elasticsearch
  ports:
  - protocol: TCP
    port: 9200
  type: NodePort
